# Generated by Django 4.2.10 on 2024-03-19 14:06

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pos_users', '0007_companyemployee_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companyemployee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='companyemployee',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='companyemployee',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id of the object'),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companyemployee',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
